### ISSUE TITLE
Liste des tâches de dév pour les fonctionnalités "Big bang"

### ISSUE THREAD

**Issue by Sabrina-Dubois** [Sabrina-Dubois/spot-me#2]
# ** TODO **

Fonctionnalité associée: #1 

## **GESTION DE PROJET**
- [x] Choix de la méthode (Kanban, workflow, definition ready/done, labels)
- [x] Mettre en place un support de communication / documentation (wiki, readme, Jira...)
- [x] Stratégie de repository branche, patterns de commentaires Git

## **CONCEPTION**
- [x] Zoning, wireframe, mock up (logo, charte graphique)
- [x] Mise en place de l'environnement (Git, GitHub, .gitignore, stratégie du repository mono ou polyr epo)
- [x] Mise en place de l'environnement de développement de base de données (DBeaver)
- [x] Mise en place de l'environnement de développement du backend (Eclipse, création et init du projet Spring boot, package...)
- [x] Mise en place de l'environnement de développement du frontend (VSCode, création et init du projet Vue, dossier -> organisation du code...)
- [x] conception de la bdd (MCD, MLD,MPD)

## **IMPLEMENTATION**
- [ ] Formulaire de saisie (validation, routeur, I18N)

**BACKEND**
- [x] Créer un ou plusieurs endpoints (controller)
- [x] Créer un ou plusieurs services (services)
- [x] Créer un ou plusieurs repository (repository)
- [x] Créer un ou plusieurs "DTO" (Data Transfer Objects)
- [x] Créer un ou plusieurs entités (entity : type de class / objet)
- [x] Back (API, validation, logique métier, communication bdd)
- [x] BDD : DDL, DML avec des spots de test 
- [x] Tester l'ensemble (UAT)

## **A VENIR**
- [ ] Déploiement
- [ ] Définition des critères d'acceptation
- [ ] Test unitaires, intégration automatisés
- [ ] Analyse statique du code (Sonar)
